from Tkinter import *

master = Tk()
Label(master, text="GPA").grid(row=0)
Label(master, text="ONET-[THAI]").grid(row=1)
Label(master, text="ONET-[SOCIAL]").grid(row=2)
Label(master, text="ONET-[ENGLISH]").grid(row=3)
Label(master, text="ONET-[MATH]").grid(row=4)
Label(master, text="ONET-[SCIENCE]").grid(row=5)
Label(master, text="ONET-[PHYCICAL]").grid(row=6)
Label(master, text="ONET-[ART]").grid(row=7)
Label(master, text="ONET-[WORK and VOCATION]").grid(row=8)
Label(master, text="GAT").grid(row=9)
Label(master, text="PAT1").grid(row=10)
Label(master, text="PAT2").grid(row=11)
Label(master, text="PAT3").grid(row=12)
Label(master, text="PAT4").grid(row=13)
Label(master, text="PAT5").grid(row=14)
Label(master, text="PAT6").grid(row=15)
Label(master, text="PAT7").grid(row=16)


e1 = Entry(master)
e2 = Entry(master)
e3 = Entry(master)
e4 = Entry(master)
e5 = Entry(master)
e6 = Entry(master)
e7 = Entry(master)
e8 = Entry(master)
e9 = Entry(master)
e10 = Entry(master)
e11 = Entry(master)
e12 = Entry(master)
e13 = Entry(master)
e14 = Entry(master)
e15 = Entry(master)
e16 = Entry(master)
e17 = Entry(master)



e1.grid(row=0, column=1)
e2.grid(row=1, column=1)
e3.grid(row=2, column=1)
e4.grid(row=3, column=1)
e5.grid(row=4, column=1)
e6.grid(row=5, column=1)
e7.grid(row=6, column=1)
e8.grid(row=7, column=1)
e9.grid(row=8, column=1)
e10.grid(row=9, column=1)
e11.grid(row=10, column=1)
e12.grid(row=11, column=1)
e13.grid(row=12, column=1)
e14.grid(row=13, column=1)
e15.grid(row=14, column=1)
e16.grid(row=15, column=1)
e17.grid(row=16, column=1)



mainloop( )
